/* ══════════════════════════════════════════════════════════════════════
   ██  LOS PASOS DE CADA TRÁMITE  ██
   ══════════════════════════════════════════════════════════════════════

   Lo lee ciip-ventanilla-unica-local.html para dibujar el detalle de un
   trámite cuando se pulsa su tarjeta.

   ─────────────────────────────────────────────────────────────────────
   POR QUÉ ESTÁ AQUÍ Y NO EN EL DICCIONARIO I18N
   ─────────────────────────────────────────────────────────────────────
   El diccionario del panel es un objeto en UNA sola línea de 57.000
   caracteres. Meterle 366 textos más lo dejaría imposible de editar a
   mano. Aquí cada trámite ocupa una línea legible y se corrige sin
   miedo.

   ─────────────────────────────────────────────────────────────────────
   CÓMO SE USA
   ─────────────────────────────────────────────────────────────────────
   Las claves c1…c21 son las mismas que ya usa el panel para el nombre
   de cada tarjeta (data-i18n="c1.name"), así que no hay una segunda
   numeración que mantener.

   Son CUATRO pasos por trámite, siempre. Dónde va cada uno NO se decide
   aquí: sale del estado de su tarjeta (data-st), para que el punto de
   avance y el distintivo de la tarjeta no puedan contradecirse.

       listo      → los cuatro hechos
       proceso    → dos hechos, el tercero en curso
       accion     → uno hecho, el segundo esperándote
       pendiente  → ninguno empezado

   ─────────────────────────────────────────────────────────────────────
   AVISO
   ─────────────────────────────────────────────────────────────────────
   Estos pasos son una RECONSTRUCCIÓN razonable de cada trámite, no una
   fuente oficial. Antes de enseñar el panel fuera del CIIP conviene que
   los revise quien tramite de verdad con cada organismo.
   ══════════════════════════════════════════════════════════════════════ */

window.CIIP_PASOS = {

  /* Título de la sección, y la etiqueta del paso en el que se está */
  titulo: {
    es: "El proceso", en: "The process", pt: "O processo",
    it: "Il processo", zh: "办理流程", ru: "Процесс"
  },
  aqui: {
    es: "Vas por aquí", en: "You are here", pt: "Está aqui",
    it: "Sei qui", zh: "当前进度", ru: "Вы здесь"
  },

  /* ═══════════════════════════════════════════════════════════════════
     LO QUE SIGUE ES DE LOS TRÁMITES QUE YA FUNCIONAN DE VERDAD
     ═══════════════════════════════════════════════════════════════════
     Las listas de arriba son decorado: describen cómo es el trámite ante
     el ente. Lo de aquí abajo describe el circuito del CIIP, que es lo
     único que la ventanilla puede saber de verdad, y sale de la base de
     datos. Un trámite usa uno u otro según esté activo en el catálogo.
     ═══════════════════════════════════════════════════════════════════ */

  /* Los cuatro estados por los que pasa una solicitud de verdad.
     {ente} se sustituye con el organismo que salga del catálogo. */
  estados: {
    es: ["Solicitud recibida por el CIIP", "Revisión de tus recaudos", "Presentada ante {ente}", "Resuelta"],
    en: ["Request received by CIIP", "Checking your documents", "Filed with {ente}", "Completed"],
    pt: ["Pedido recebido pelo CIIP", "Verificação dos seus documentos", "Apresentado ao {ente}", "Concluído"],
    it: ["Richiesta ricevuta dal CIIP", "Verifica dei tuoi documenti", "Presentata a {ente}", "Conclusa"],
    zh: ["CIIP 已收到申请", "核验您的材料", "已向 {ente} 提交", "已办结"],
    ru: ["Заявка получена CIIP", "Проверка ваших документов", "Подано в {ente}", "Завершено"]
  },

  /* Textos del formulario y de los avisos */
  ui: {
    es: {
      iniciar:      "Iniciar esta solicitud",
      tus_datos:    "Tus datos",
      recaudos:     "Recaudos",
      enviar:       "Enviar solicitud",
      enviando:     "Enviando…",
      guardado:     "Solicitud enviada",
      tu_solicitud: "Tu solicitud",
      enviada_el:   "Enviada el",
      adjuntos:     "Recaudos entregados",
      devuelta:     "Te la devolvimos: falta algo",
      falta:        "Rellena los campos marcados",
      sin_archivo:  "Elige el archivo",
      error:        "No se pudo enviar. Inténtalo otra vez.",
      reutilizado:  "ya estaba en tu expediente",
      f_tipodoc:    "Documento de identidad",
      f_numero:     "Número",
      f_nacimiento: "Fecha de nacimiento",
      f_direccion:  "Dirección fiscal en Venezuela",
      f_telefono:   "Teléfono",
      f_profesion:  "Profesión u oficio",
      d_identidad:  "Cédula o pasaporte",
      d_domicilio:  "Comprobante de domicilio",
      /* --- RIF de la empresa --- */
      f_razon:       "Razón social",
      f_registro:    "N.º de Registro Mercantil",
      f_constitucion:"Fecha de constitución",
      f_actividad:   "Actividad económica",
      f_capital:     "Capital social",
      d_acta:        "Acta constitutiva",
      d_rifpersonal: "Tu RIF personal",
      d_domemp:      "Domicilio fiscal de la empresa",
      /* --- Visa de inversionista (SAIME) --- */
      f_pasaporte:   "N.º de pasaporte",
      f_paisemisor:  "País emisor del pasaporte",
      f_vencepas:    "Vencimiento del pasaporte",
      f_consulado:   "Consulado donde tramitas",
      f_montoinv:    "Monto estimado de la inversión",
      f_motivo:      "En qué vas a invertir",
      d_pasaporte:   "Pasaporte vigente",
      d_foto:        "Fotografía tipo carnet",
      d_antecedentes:"Antecedentes penales apostillados",
      d_inversion:   "Constancia de la inversión",
      /* --- Cédula de residencia (SAIME) --- */
      f_numvisa:     "N.º de visa",
      f_ingreso:     "Fecha de entrada al país",
      f_dirvzla:     "Dirección en Venezuela",
      f_telvzla:     "Teléfono en Venezuela",
      f_civil:       "Estado civil",
      f_ocupacion:   "Ocupación",
      o_civil:       ["Soltero/a", "Casado/a", "Divorciado/a", "Viudo/a"],
      d_visa:        "Visa vigente",
      /* --- Homologación de licencia de conducir (INTT) --- */
      f_numlic:      "N.º de la licencia",
      f_paislic:     "País que la emitió",
      f_catlic:      "Categoría",
      f_emisionlic:  "Fecha de emisión",
      f_vencelic:    "Vencimiento de la licencia",
      d_licencia:    "Licencia de conducir extranjera",
      d_traduccion:  "Traducción certificada de la licencia",
      d_medico:      "Certificado médico",
      /* --- Constitución de la compañía (SAREN) --- */
      f_denominacion:"Nombre de la compañía",
      f_denomalt:    "Segunda opción de nombre",
      f_tiposoc:     "Tipo de sociedad",
      o_tiposoc:     ["Compañía Anónima (C.A.)", "Sociedad Anónima (S.A.)", "Sociedad de Responsabilidad Limitada (S.R.L.)", "Firma personal"],
      f_objeto:      "Objeto social",
      f_domsocial:   "Domicilio de la compañía",
      f_socios:      "Socios y su participación",
      d_capital:     "Comprobante del capital (depósito o inventario)",
      /* --- Cuenta bancaria corporativa (banca aliada) --- */
      f_rifempresa:  "N.º de RIF de la empresa",
      f_tipocuenta:  "Tipo de cuenta",
      o_tipocuenta:  ["Corriente", "Ahorro"],
      f_moneda:      "Moneda de la cuenta",
      o_moneda:      ["Bolívares", "Divisas (USD)"],
      f_firmantes:   "Firmantes autorizados y forma de firma",
      f_movimiento:  "Movimiento mensual estimado",
      f_origenfondos:"Origen de los fondos",
      f_ciudad:      "Ciudad donde prefieres la agencia",
      d_rifempresa:  "RIF de la empresa",
      banco_asignado:"Banco aliado",
      banco_pendiente:"Todavía sin asignar — te lo confirmamos antes de la cita",
      /* --- Registro de marca (SAPI) --- */
      f_signo:       "Nombre o denominación de la marca",
      f_tiposigno:   "Tipo de signo",
      o_tiposigno:   ["Denominativa (solo palabra)", "Figurativa (solo diseño)", "Mixta (palabra y diseño)"],
      f_titular:     "A nombre de quién se registra",
      o_titular:     ["La empresa", "Yo, como persona natural"],
      f_enuso:       "¿Ya usas la marca?",
      o_enuso:       ["Todavía no", "Sí, ya la uso"],
      f_productos:   "Productos o servicios que ampara",
      d_logo:        "Logotipo o diseño de la marca",
      /* --- Registros laborales (IVSS · INCES · FAOV) --- */
      f_representante:"Representante legal (patrono)",
      f_iniciolab:   "Fecha de inicio de actividades",
      f_numtrab:     "N.º de trabajadores a inscribir",
      d_nomina:      "Nómina de trabajadores",
      opcional:      "(opcional)",
      /* --- Licencia de funcionamiento (Alcaldía) --- */
      f_municipio:   "Municipio donde está el local",
      f_tenencia:    "El local es",
      o_tenencia:    ["Propio", "Alquilado"],
      f_metros:      "Metros cuadrados del local",
      f_dirlocal:    "Dirección exacta del local o planta",
      d_inmueble:    "Título de propiedad o contrato de arrendamiento",
      d_bomberos:    "Conformidad de bomberos",
      /* --- Fase 01: los seis trámites que faltaban --- */
      f_paisorigen:    "País que emite el certificado",
      f_autoridad:     "Autoridad que lo emitió",
      f_fechacert:     "Fecha del certificado",
      f_idioma:        "Idioma del documento",
      f_docapost:      "Documento a apostillar",
      o_docapost:      ["Partida de nacimiento", "Acta de matrimonio", "Título universitario", "Otro"],
      f_fechadoc:      "Fecha del documento",
      f_uso:           "Para qué lo necesitas",
      f_ciudadvzla:    "Ciudad en Venezuela",
      f_municipiovzla: "Municipio",
      f_tipovivienda:  "La vivienda es",
      o_tipovivienda:  ["Propia", "Alquilada", "Cedida"],
      f_tiempores:     "Tiempo viviendo allí",
      f_correocert:    "Correo para el certificado",
      f_tipocert:      "Tipo de certificado",
      o_tipocert:      ["Persona natural", "Representante de empresa"],
      f_nomdep:        "Nombre completo del familiar",
      f_parentesco:    "Parentesco",
      o_parentesco:    ["Cónyuge", "Hijo o hija", "Padre o madre"],
      f_centro:        "Centro de salud",
      f_tipoexamen:    "Tipo de examen",
      o_tipoexamen:    ["Médico general", "Médico vial", "Otro"],
      d_antecorigen:   "Antecedentes penales de tu país",
      d_original:      "Documento original a apostillar",
      d_arrendamiento: "Contrato de arrendamiento o carta de residencia",
      d_recibo:        "Recibo de un servicio público",
      d_pasdep:        "Pasaporte del familiar",
      d_vinculo:       "Acta que acredita el vínculo",
      d_fotodep:       "Fotografía tipo carnet del familiar",
      /* --- Fase 02: protocolización, publicación y libros --- */
      f_registromerc: "Registro Mercantil donde protocolizas",
      f_fechafirma:   "Fecha de firma del documento",
      f_fechaprot:    "Fecha de protocolización",
      f_periodico:    "Periódico mercantil preferido",
      f_tipofact:     "Cómo vas a facturar",
      o_tipofact:     ["Imprenta autorizada", "Máquina fiscal", "Sistema homologado"],
      d_aranceles:    "Comprobante del pago de aranceles",
      d_actaprot:     "Acta constitutiva protocolizada"
    },
    en: {
      iniciar:      "Start this request",
      tus_datos:    "Your details",
      recaudos:     "Documents",
      enviar:       "Send request",
      enviando:     "Sending…",
      guardado:     "Request sent",
      tu_solicitud: "Your request",
      enviada_el:   "Sent on",
      adjuntos:     "Documents provided",
      devuelta:     "Sent back to you: something is missing",
      falta:        "Fill in the highlighted fields",
      sin_archivo:  "Choose the file",
      error:        "It could not be sent. Please try again.",
      reutilizado:  "already in your file",
      f_tipodoc:    "Identity document",
      f_numero:     "Number",
      f_nacimiento: "Date of birth",
      f_direccion:  "Tax address in Venezuela",
      f_telefono:   "Phone",
      f_profesion:  "Occupation",
      d_identidad:  "ID card or passport",
      d_domicilio:  "Proof of address",
      /* --- RIF de la empresa --- */
      f_razon:       "Company name",
      f_registro:    "Mercantile Registry number",
      f_constitucion:"Date of incorporation",
      f_actividad:   "Business activity",
      f_capital:     "Share capital",
      d_acta:        "Articles of incorporation",
      d_rifpersonal: "Your personal RIF",
      d_domemp:      "Company tax address proof",
      /* --- Investor visa (SAIME) --- */
      f_pasaporte:   "Passport number",
      f_paisemisor:  "Passport issuing country",
      f_vencepas:    "Passport expiry date",
      f_consulado:   "Consulate handling your application",
      f_montoinv:    "Estimated investment amount",
      f_motivo:      "What you will invest in",
      d_pasaporte:   "Valid passport",
      d_foto:        "Passport-size photograph",
      d_antecedentes:"Apostilled criminal record certificate",
      d_inversion:   "Proof of investment",
      /* --- Residence card (SAIME) --- */
      f_numvisa:     "Visa number",
      f_ingreso:     "Date of entry into the country",
      f_dirvzla:     "Address in Venezuela",
      f_telvzla:     "Phone number in Venezuela",
      f_civil:       "Marital status",
      f_ocupacion:   "Occupation",
      o_civil:       ["Single", "Married", "Divorced", "Widowed"],
      d_visa:        "Valid visa",
      /* --- Driving licence conversion (INTT) --- */
      f_numlic:      "Licence number",
      f_paislic:     "Issuing country",
      f_catlic:      "Category",
      f_emisionlic:  "Date of issue",
      f_vencelic:    "Licence expiry date",
      d_licencia:    "Foreign driving licence",
      d_traduccion:  "Certified translation of the licence",
      d_medico:      "Medical certificate",
      /* --- Company incorporation (SAREN) --- */
      f_denominacion:"Company name",
      f_denomalt:    "Second name choice",
      f_tiposoc:     "Type of company",
      o_tiposoc:     ["Public limited company (C.A.)", "Joint-stock company (S.A.)", "Limited liability company (S.R.L.)", "Sole trader"],
      f_objeto:      "Business purpose",
      f_domsocial:   "Registered address of the company",
      f_socios:      "Shareholders and their stakes",
      d_capital:     "Proof of capital (bank deposit or asset inventory)",
      /* --- Corporate bank account (partner banks) --- */
      f_rifempresa:  "Company RIF number",
      f_tipocuenta:  "Account type",
      o_tipocuenta:  ["Current account", "Savings account"],
      f_moneda:      "Account currency",
      o_moneda:      ["Bolívares", "Foreign currency (USD)"],
      f_firmantes:   "Authorised signatories and signing rules",
      f_movimiento:  "Estimated monthly turnover",
      f_origenfondos:"Source of funds",
      f_ciudad:      "Preferred city for the branch",
      d_rifempresa:  "Company RIF",
      banco_asignado:"Partner bank",
      banco_pendiente:"Not assigned yet — we will confirm it before the appointment",
      /* --- Trademark registration (SAPI) --- */
      f_signo:       "Trademark name",
      f_tiposigno:   "Type of sign",
      o_tiposigno:   ["Word mark (text only)", "Figurative (design only)", "Combined (text and design)"],
      f_titular:     "Registered in the name of",
      o_titular:     ["The company", "Myself, as an individual"],
      f_enuso:       "Are you already using the mark?",
      o_enuso:       ["Not yet", "Yes, already in use"],
      f_productos:   "Goods or services it covers",
      d_logo:        "Trademark logo or design",
      /* --- Labour registrations (IVSS · INCES · FAOV) --- */
      f_representante:"Legal representative (employer)",
      f_iniciolab:   "Date operations started",
      f_numtrab:     "Number of employees to enrol",
      d_nomina:      "Payroll list",
      opcional:      "(optional)",
      /* --- Municipal operating licence (Mayor’s office) --- */
      f_municipio:   "Municipality where the premises are",
      f_tenencia:    "The premises are",
      o_tenencia:    ["Owned", "Rented"],
      f_metros:      "Floor area in square metres",
      f_dirlocal:    "Exact address of the premises or plant",
      d_inmueble:    "Title deed or lease agreement",
      d_bomberos:    "Fire department clearance",
      /* --- Fase 01: los seis trámites que faltaban --- */
      f_paisorigen:    "Country issuing the certificate",
      f_autoridad:     "Issuing authority",
      f_fechacert:     "Certificate date",
      f_idioma:        "Language of the document",
      f_docapost:      "Document to be apostilled",
      o_docapost:      ["Birth certificate", "Marriage certificate", "University degree", "Other"],
      f_fechadoc:      "Document date",
      f_uso:           "What you need it for",
      f_ciudadvzla:    "City in Venezuela",
      f_municipiovzla: "Municipality",
      f_tipovivienda:  "The home is",
      o_tipovivienda:  ["Owned", "Rented", "Lent"],
      f_tiempores:     "How long you have lived there",
      f_correocert:    "Email for the certificate",
      f_tipocert:      "Type of certificate",
      o_tipocert:      ["Individual", "Company representative"],
      f_nomdep:        "Full name of the family member",
      f_parentesco:    "Relationship",
      o_parentesco:    ["Spouse", "Son or daughter", "Parent"],
      f_centro:        "Health centre",
      f_tipoexamen:    "Type of examination",
      o_tipoexamen:    ["General medical", "Driving medical", "Other"],
      d_antecorigen:   "Criminal record from your country",
      d_original:      "Original document to be apostilled",
      d_arrendamiento: "Lease or proof-of-residence letter",
      d_recibo:        "Utility bill",
      d_pasdep:        "Passport of the family member",
      d_vinculo:       "Certificate proving the relationship",
      d_fotodep:       "Passport photo of the family member",
      /* --- Fase 02: protocolización, publicación y libros --- */
      f_registromerc: "Mercantile Registry where you file",
      f_fechafirma:   "Date the document was signed",
      f_fechaprot:    "Filing date",
      f_periodico:    "Preferred mercantile newspaper",
      f_tipofact:     "How you will invoice",
      o_tipofact:     ["Authorised printer", "Fiscal machine", "Approved system"],
      d_aranceles:    "Proof of payment of registry fees",
      d_actaprot:     "Filed articles of incorporation"
    },
    pt: {
      iniciar:      "Iniciar este pedido",
      tus_datos:    "Os seus dados",
      recaudos:     "Documentos",
      enviar:       "Enviar pedido",
      enviando:     "A enviar…",
      guardado:     "Pedido enviado",
      tu_solicitud: "O seu pedido",
      enviada_el:   "Enviado em",
      adjuntos:     "Documentos entregues",
      devuelta:     "Devolvido: falta alguma coisa",
      falta:        "Preencha os campos assinalados",
      sin_archivo:  "Escolha o ficheiro",
      error:        "Não foi possível enviar. Tente outra vez.",
      reutilizado:  "já estava no seu processo",
      f_tipodoc:    "Documento de identidade",
      f_numero:     "Número",
      f_nacimiento: "Data de nascimento",
      f_direccion:  "Morada fiscal na Venezuela",
      f_telefono:   "Telefone",
      f_profesion:  "Profissão",
      d_identidad:  "Cartão de cidadão ou passaporte",
      d_domicilio:  "Comprovativo de morada",
      /* --- RIF de la empresa --- */
      f_razon:       "Denominação social",
      f_registro:    "N.º do Registo Comercial",
      f_constitucion:"Data de constituição",
      f_actividad:   "Atividade económica",
      f_capital:     "Capital social",
      d_acta:        "Pacto social",
      d_rifpersonal: "O seu RIF pessoal",
      d_domemp:      "Comprovativo de morada fiscal da empresa",
      /* --- Visto de investidor (SAIME) --- */
      f_pasaporte:   "N.º do passaporte",
      f_paisemisor:  "País emissor do passaporte",
      f_vencepas:    "Validade do passaporte",
      f_consulado:   "Consulado onde tramita",
      f_montoinv:    "Valor estimado do investimento",
      f_motivo:      "Em que vai investir",
      d_pasaporte:   "Passaporte válido",
      d_foto:        "Fotografia tipo passe",
      d_antecedentes:"Registo criminal apostilado",
      d_inversion:   "Comprovativo do investimento",
      /* --- Cartão de residência (SAIME) --- */
      f_numvisa:     "N.º do visto",
      f_ingreso:     "Data de entrada no país",
      f_dirvzla:     "Morada na Venezuela",
      f_telvzla:     "Telefone na Venezuela",
      f_civil:       "Estado civil",
      f_ocupacion:   "Ocupação",
      o_civil:       ["Solteiro/a", "Casado/a", "Divorciado/a", "Viúvo/a"],
      d_visa:        "Visto válido",
      /* --- Homologação da carta de condução (INTT) --- */
      f_numlic:      "N.º da carta",
      f_paislic:     "País emissor",
      f_catlic:      "Categoria",
      f_emisionlic:  "Data de emissão",
      f_vencelic:    "Validade da carta",
      d_licencia:    "Carta de condução estrangeira",
      d_traduccion:  "Tradução certificada da carta",
      d_medico:      "Atestado médico",
      /* --- Constituição da empresa (SAREN) --- */
      f_denominacion:"Nome da empresa",
      f_denomalt:    "Segunda opção de nome",
      f_tiposoc:     "Tipo de sociedade",
      o_tiposoc:     ["Companhia Anónima (C.A.)", "Sociedade Anónima (S.A.)", "Sociedade por Quotas (S.R.L.)", "Empresário em nome individual"],
      f_objeto:      "Objeto social",
      f_domsocial:   "Sede da empresa",
      f_socios:      "Sócios e respetivas participações",
      d_capital:     "Comprovativo do capital (depósito ou inventário)",
      /* --- Conta bancária da empresa (banca parceira) --- */
      f_rifempresa:  "N.º de RIF da empresa",
      f_tipocuenta:  "Tipo de conta",
      o_tipocuenta:  ["à ordem", "Poupança"],
      f_moneda:      "Moeda da conta",
      o_moneda:      ["Bolívares", "Divisas (USD)"],
      f_firmantes:   "Pessoas autorizadas a assinar e forma de assinatura",
      f_movimiento:  "Movimento mensal estimado",
      f_origenfondos:"Origem dos fundos",
      f_ciudad:      "Cidade onde prefere o balcão",
      d_rifempresa:  "RIF da empresa",
      banco_asignado:"Banco parceiro",
      banco_pendiente:"Ainda por atribuir — confirmamos antes da marcação",
      /* --- Registo de marca (SAPI) --- */
      f_signo:       "Nome ou denominação da marca",
      f_tiposigno:   "Tipo de sinal",
      o_tiposigno:   ["Nominativa (só palavra)", "Figurativa (só desenho)", "Mista (palavra e desenho)"],
      f_titular:     "Em nome de quem se regista",
      o_titular:     ["A empresa", "Eu, como pessoa singular"],
      f_enuso:       "Já usa a marca?",
      o_enuso:       ["Ainda não", "Sim, já a uso"],
      f_productos:   "Produtos ou serviços que abrange",
      d_logo:        "Logótipo ou desenho da marca",
      /* --- Registos laborais (IVSS · INCES · FAOV) --- */
      f_representante:"Representante legal (entidade patronal)",
      f_iniciolab:   "Data de início da atividade",
      f_numtrab:     "N.º de trabalhadores a inscrever",
      d_nomina:      "Folha de trabalhadores",
      opcional:      "(facultativo)",
      /* --- Alvará de funcionamento (Câmara) --- */
      f_municipio:   "Município onde está o estabelecimento",
      f_tenencia:    "O espaço é",
      o_tenencia:    ["Próprio", "Arrendado"],
      f_metros:      "Metros quadrados do espaço",
      f_dirlocal:    "Morada exata do estabelecimento ou fábrica",
      d_inmueble:    "Título de propriedade ou contrato de arrendamento",
      d_bomberos:    "Parecer dos bombeiros",
      /* --- Fase 01: los seis trámites que faltaban --- */
      f_paisorigen:    "País que emite o certificado",
      f_autoridad:     "Autoridade que o emitiu",
      f_fechacert:     "Data do certificado",
      f_idioma:        "Idioma do documento",
      f_docapost:      "Documento a apostilar",
      o_docapost:      ["Certidão de nascimento", "Certidão de casamento", "Diploma universitário", "Outro"],
      f_fechadoc:      "Data do documento",
      f_uso:           "Para que precisa dele",
      f_ciudadvzla:    "Cidade na Venezuela",
      f_municipiovzla: "Município",
      f_tipovivienda:  "A moradia é",
      o_tipovivienda:  ["Própria", "Alugada", "Cedida"],
      f_tiempores:     "Há quanto tempo mora lá",
      f_correocert:    "E-mail para o certificado",
      f_tipocert:      "Tipo de certificado",
      o_tipocert:      ["Pessoa física", "Representante de empresa"],
      f_nomdep:        "Nome completo do familiar",
      f_parentesco:    "Parentesco",
      o_parentesco:    ["Cônjuge", "Filho ou filha", "Pai ou mãe"],
      f_centro:        "Centro de saúde",
      f_tipoexamen:    "Tipo de exame",
      o_tipoexamen:    ["Médico geral", "Médico de trânsito", "Outro"],
      d_antecorigen:   "Antecedentes criminais do seu país",
      d_original:      "Documento original a apostilar",
      d_arrendamiento: "Contrato de arrendamento ou carta de residência",
      d_recibo:        "Conta de um serviço público",
      d_pasdep:        "Passaporte do familiar",
      d_vinculo:       "Certidão que comprova o vínculo",
      d_fotodep:       "Fotografia tipo passe do familiar",
      /* --- Fase 02: protocolización, publicación y libros --- */
      f_registromerc: "Registro Mercantil onde protocoliza",
      f_fechafirma:   "Data de assinatura do documento",
      f_fechaprot:    "Data de protocolização",
      f_periodico:    "Jornal mercantil preferido",
      f_tipofact:     "Como vai faturar",
      o_tipofact:     ["Gráfica autorizada", "Máquina fiscal", "Sistema homologado"],
      d_aranceles:    "Comprovante do pagamento das taxas",
      d_actaprot:     "Ata constitutiva protocolizada"
    },
    it: {
      iniciar:      "Avvia questa richiesta",
      tus_datos:    "I tuoi dati",
      recaudos:     "Documenti",
      enviar:       "Invia richiesta",
      enviando:     "Invio in corso…",
      guardado:     "Richiesta inviata",
      tu_solicitud: "La tua richiesta",
      enviada_el:   "Inviata il",
      adjuntos:     "Documenti consegnati",
      devuelta:     "Te l'abbiamo rimandata: manca qualcosa",
      falta:        "Compila i campi evidenziati",
      sin_archivo:  "Scegli il file",
      error:        "Non è stato possibile inviarla. Riprova.",
      reutilizado:  "era già nella tua pratica",
      f_tipodoc:    "Documento d'identità",
      f_numero:     "Numero",
      f_nacimiento: "Data di nascita",
      f_direccion:  "Indirizzo fiscale in Venezuela",
      f_telefono:   "Telefono",
      f_profesion:  "Professione",
      d_identidad:  "Carta d'identità o passaporto",
      d_domicilio:  "Prova di residenza",
      /* --- RIF de la empresa --- */
      f_razon:       "Ragione sociale",
      f_registro:    "N. del Registro delle Imprese",
      f_constitucion:"Data di costituzione",
      f_actividad:   "Attività economica",
      f_capital:     "Capitale sociale",
      d_acta:        "Atto costitutivo",
      d_rifpersonal: "Il tuo RIF personale",
      d_domemp:      "Prova della sede fiscale",
      /* --- Visto per investitori (SAIME) --- */
      f_pasaporte:   "N. di passaporto",
      f_paisemisor:  "Paese di rilascio del passaporto",
      f_vencepas:    "Scadenza del passaporto",
      f_consulado:   "Consolato presso cui presenti la domanda",
      f_montoinv:    "Importo stimato dell'investimento",
      f_motivo:      "In cosa investirai",
      d_pasaporte:   "Passaporto valido",
      d_foto:        "Fototessera",
      d_antecedentes:"Certificato penale con apostille",
      d_inversion:   "Prova dell'investimento",
      /* --- Permesso di soggiorno (SAIME) --- */
      f_numvisa:     "N. del visto",
      f_ingreso:     "Data di ingresso nel Paese",
      f_dirvzla:     "Indirizzo in Venezuela",
      f_telvzla:     "Telefono in Venezuela",
      f_civil:       "Stato civile",
      f_ocupacion:   "Occupazione",
      o_civil:       ["Celibe/Nubile", "Coniugato/a", "Divorziato/a", "Vedovo/a"],
      d_visa:        "Visto valido",
      /* --- Conversione della patente (INTT) --- */
      f_numlic:      "N. della patente",
      f_paislic:     "Paese di rilascio",
      f_catlic:      "Categoria",
      f_emisionlic:  "Data di rilascio",
      f_vencelic:    "Scadenza della patente",
      d_licencia:    "Patente estera",
      d_traduccion:  "Traduzione giurata della patente",
      d_medico:      "Certificato medico",
      /* --- Costituzione della società (SAREN) --- */
      f_denominacion:"Denominazione della società",
      f_denomalt:    "Seconda scelta di denominazione",
      f_tiposoc:     "Tipo di società",
      o_tiposoc:     ["Società per azioni (C.A.)", "Società anonima (S.A.)", "Società a responsabilità limitata (S.R.L.)", "Ditta individuale"],
      f_objeto:      "Oggetto sociale",
      f_domsocial:   "Sede della società",
      f_socios:      "Soci e relative quote",
      d_capital:     "Prova del capitale (versamento o inventario dei beni)",
      /* --- Conto corrente aziendale (banche partner) --- */
      f_rifempresa:  "Numero RIF della società",
      f_tipocuenta:  "Tipo di conto",
      o_tipocuenta:  ["Conto corrente", "Conto di risparmio"],
      f_moneda:      "Valuta del conto",
      o_moneda:      ["Bolívar", "Valuta estera (USD)"],
      f_firmantes:   "Firmatari autorizzati e modalità di firma",
      f_movimiento:  "Movimentazione mensile stimata",
      f_origenfondos:"Origine dei fondi",
      f_ciudad:      "Città in cui preferisci la filiale",
      d_rifempresa:  "RIF della società",
      banco_asignado:"Banca partner",
      banco_pendiente:"Non ancora assegnata — te lo confermiamo prima dell’appuntamento",
      /* --- Registrazione del marchio (SAPI) --- */
      f_signo:       "Nome o denominazione del marchio",
      f_tiposigno:   "Tipo di segno",
      o_tiposigno:   ["Denominativo (solo parola)", "Figurativo (solo disegno)", "Misto (parola e disegno)"],
      f_titular:     "A nome di chi si registra",
      o_titular:     ["La società", "Io, come persona fisica"],
      f_enuso:       "Usi già il marchio?",
      o_enuso:       ["Non ancora", "Sì, lo uso già"],
      f_productos:   "Prodotti o servizi che copre",
      d_logo:        "Logo o disegno del marchio",
      /* --- Registrazioni del lavoro (IVSS · INCES · FAOV) --- */
      f_representante:"Rappresentante legale (datore di lavoro)",
      f_iniciolab:   "Data di inizio dell’attività",
      f_numtrab:     "Numero di dipendenti da iscrivere",
      d_nomina:      "Elenco dei dipendenti",
      opcional:      "(facoltativo)",
      /* --- Licenza di esercizio (Comune) --- */
      f_municipio:   "Comune in cui si trova il locale",
      f_tenencia:    "Il locale è",
      o_tenencia:    ["Di proprietà", "In affitto"],
      f_metros:      "Metri quadri del locale",
      f_dirlocal:    "Indirizzo esatto del locale o dello stabilimento",
      d_inmueble:    "Atto di proprietà o contratto di locazione",
      d_bomberos:    "Certificato dei vigili del fuoco",
      /* --- Fase 01: los seis trámites que faltaban --- */
      f_paisorigen:    "Paese che rilascia il certificato",
      f_autoridad:     "Autorità che lo ha rilasciato",
      f_fechacert:     "Data del certificato",
      f_idioma:        "Lingua del documento",
      f_docapost:      "Documento da apostillare",
      o_docapost:      ["Atto di nascita", "Atto di matrimonio", "Titolo universitario", "Altro"],
      f_fechadoc:      "Data del documento",
      f_uso:           "A cosa ti serve",
      f_ciudadvzla:    "Città in Venezuela",
      f_municipiovzla: "Comune",
      f_tipovivienda:  "L’abitazione è",
      o_tipovivienda:  ["Di proprietà", "In affitto", "In comodato"],
      f_tiempores:     "Da quanto tempo ci vivi",
      f_correocert:    "Email per il certificato",
      f_tipocert:      "Tipo di certificato",
      o_tipocert:      ["Persona fisica", "Rappresentante d’impresa"],
      f_nomdep:        "Nome completo del familiare",
      f_parentesco:    "Grado di parentela",
      o_parentesco:    ["Coniuge", "Figlio o figlia", "Genitore"],
      f_centro:        "Struttura sanitaria",
      f_tipoexamen:    "Tipo di visita",
      o_tipoexamen:    ["Medica generale", "Medica per la patente", "Altro"],
      d_antecorigen:   "Casellario giudiziale del tuo paese",
      d_original:      "Documento originale da apostillare",
      d_arrendamiento: "Contratto d’affitto o attestazione di residenza",
      d_recibo:        "Bolletta di un’utenza",
      d_pasdep:        "Passaporto del familiare",
      d_vinculo:       "Atto che prova il legame",
      d_fotodep:       "Foto tessera del familiare",
      /* --- Fase 02: protocolización, publicación y libros --- */
      f_registromerc: "Registro delle Imprese dove depositi",
      f_fechafirma:   "Data di firma dell’atto",
      f_fechaprot:    "Data di deposito",
      f_periodico:    "Giornale commerciale preferito",
      f_tipofact:     "Come emetterai le fatture",
      o_tipofact:     ["Tipografia autorizzata", "Registratore fiscale", "Sistema omologato"],
      d_aranceles:    "Ricevuta dei diritti di registro",
      d_actaprot:     "Atto costitutivo depositato"
    },
    zh: {
      iniciar:      "开始办理",
      tus_datos:    "您的资料",
      recaudos:     "材料",
      enviar:       "提交申请",
      enviando:     "提交中…",
      guardado:     "申请已提交",
      tu_solicitud: "您的申请",
      enviada_el:   "提交于",
      adjuntos:     "已提交的材料",
      devuelta:     "已退回：还缺材料",
      falta:        "请填写标注的字段",
      sin_archivo:  "请选择文件",
      error:        "提交失败，请重试。",
      reutilizado:  "档案中已有",
      f_tipodoc:    "身份证件",
      f_numero:     "证件号码",
      f_nacimiento: "出生日期",
      f_direccion:  "在委内瑞拉的税务地址",
      f_telefono:   "电话",
      f_profesion:  "职业",
      d_identidad:  "身份证或护照",
      d_domicilio:  "住址证明",
      /* --- RIF de la empresa --- */
      f_razon:       "公司名称",
      f_registro:    "商业登记号",
      f_constitucion:"成立日期",
      f_actividad:   "经营范围",
      f_capital:     "注册资本",
      d_acta:        "公司章程",
      d_rifpersonal: "您的个人 RIF",
      d_domemp:      "公司税务地址证明",
      /* --- 投资者签证（SAIME） --- */
      f_pasaporte:   "护照号码",
      f_paisemisor:  "护照签发国",
      f_vencepas:    "护照有效期至",
      f_consulado:   "办理签证的领事馆",
      f_montoinv:    "预计投资金额",
      f_motivo:      "投资方向",
      d_pasaporte:   "有效护照",
      d_foto:        "证件照",
      d_antecedentes:"经认证的无犯罪记录证明",
      d_inversion:   "投资证明",
      /* --- 居留证（SAIME） --- */
      f_numvisa:     "签证号码",
      f_ingreso:     "入境日期",
      f_dirvzla:     "在委内瑞拉的住址",
      f_telvzla:     "在委内瑞拉的电话",
      f_civil:       "婚姻状况",
      f_ocupacion:   "职业",
      o_civil:       ["未婚", "已婚", "离异", "丧偶"],
      d_visa:        "有效签证",
      /* --- 驾照换领（INTT） --- */
      f_numlic:      "驾照号码",
      f_paislic:     "签发国家",
      f_catlic:      "准驾类别",
      f_emisionlic:  "签发日期",
      f_vencelic:    "驾照有效期至",
      d_licencia:    "外国驾照",
      d_traduccion:  "驾照的认证翻译件",
      d_medico:      "健康证明",
      /* --- 公司设立（SAREN） --- */
      f_denominacion:"公司名称",
      f_denomalt:    "备选公司名称",
      f_tiposoc:     "公司类型",
      o_tiposoc:     ["股份公司（C.A.）", "股份有限公司（S.A.）", "有限责任公司（S.R.L.）", "个人商号"],
      f_objeto:      "经营范围",
      f_domsocial:   "公司注册地址",
      f_socios:      "股东及持股比例",
      d_capital:     "资本金证明（银行存款或资产清单）",
      /* --- 公司银行账户（合作银行） --- */
      f_rifempresa:  "公司 RIF 号码",
      f_tipocuenta:  "账户类型",
      o_tipocuenta:  ["活期账户", "储蓄账户"],
      f_moneda:      "账户币种",
      o_moneda:      ["玻利瓦尔", "外币（美元）"],
      f_firmantes:   "授权签字人及签字方式",
      f_movimiento:  "预估每月流水",
      f_origenfondos:"资金来源",
      f_ciudad:      "希望办理的城市",
      d_rifempresa:  "公司 RIF",
      banco_asignado:"合作银行",
      banco_pendiente:"尚未安排 — 预约前会告知您",
      /* --- 商标注册（SAPI） --- */
      f_signo:       "商标名称",
      f_tiposigno:   "商标类型",
      o_tiposigno:   ["文字商标（仅文字）", "图形商标（仅图形）", "组合商标（文字加图形）"],
      f_titular:     "注册人",
      o_titular:     ["公司", "本人（自然人）"],
      f_enuso:       "商标已在使用了吗？",
      o_enuso:       ["尚未使用", "是，已在使用"],
      f_productos:   "核定的商品或服务",
      d_logo:        "商标图样或设计",
      /* --- 劳动登记（IVSS · INCES · FAOV） --- */
      f_representante:"法定代表人（雇主）",
      f_iniciolab:   "开业日期",
      f_numtrab:     "拟登记员工人数",
      d_nomina:      "员工名册",
      opcional:      "（选填）",
      /* --- 市政营业执照（市政府） --- */
      f_municipio:   "营业场所所在市镇",
      f_tenencia:    "场所性质",
      o_tenencia:    ["自有", "租赁"],
      f_metros:      "场所面积（平方米）",
      f_dirlocal:    "营业场所或厂房详细地址",
      d_inmueble:    "产权证或租赁合同",
      d_bomberos:    "消防合格证明",
      /* --- Fase 01: los seis trámites que faltaban --- */
      f_paisorigen:    "证明签发国",
      f_autoridad:     "签发机关",
      f_fechacert:     "证明签发日期",
      f_idioma:        "文件语言",
      f_docapost:      "需认证的文件",
      o_docapost:      ["出生证明", "结婚证", "大学学位证", "其他"],
      f_fechadoc:      "文件日期",
      f_uso:           "用途",
      f_ciudadvzla:    "委内瑞拉的城市",
      f_municipiovzla: "市镇",
      f_tipovivienda:  "住所属于",
      o_tipovivienda:  ["自有", "租赁", "借住"],
      f_tiempores:     "居住时长",
      f_correocert:    "接收证书的邮箱",
      f_tipocert:      "证书类型",
      o_tipocert:      ["自然人", "企业代表"],
      f_nomdep:        "家属全名",
      f_parentesco:    "亲属关系",
      o_parentesco:    ["配偶", "子女", "父母"],
      f_centro:        "医疗机构",
      f_tipoexamen:    "体检类型",
      o_tipoexamen:    ["普通体检", "驾驶体检", "其他"],
      d_antecorigen:   "原籍国无犯罪记录证明",
      d_original:      "待认证的文件原件",
      d_arrendamiento: "租赁合同或居住证明信",
      d_recibo:        "公共事业账单",
      d_pasdep:        "家属护照",
      d_vinculo:       "证明亲属关系的证书",
      d_fotodep:       "家属证件照",
      /* --- Fase 02: protocolización, publicación y libros --- */
      f_registromerc: "办理登记的商事登记处",
      f_fechafirma:   "文件签署日期",
      f_fechaprot:    "登记日期",
      f_periodico:    "首选商事报纸",
      f_tipofact:     "开票方式",
      o_tipofact:     ["授权印刷厂", "税控机", "认证系统"],
      d_aranceles:    "登记规费缴纳凭证",
      d_actaprot:     "已登记的公司章程"
    },
    ru: {
      iniciar:      "Начать заявку",
      tus_datos:    "Ваши данные",
      recaudos:     "Документы",
      enviar:       "Отправить заявку",
      enviando:     "Отправка…",
      guardado:     "Заявка отправлена",
      tu_solicitud: "Ваша заявка",
      enviada_el:   "Отправлена",
      adjuntos:     "Переданные документы",
      devuelta:     "Возвращена: чего-то не хватает",
      falta:        "Заполните отмеченные поля",
      sin_archivo:  "Выберите файл",
      error:        "Не удалось отправить. Попробуйте ещё раз.",
      reutilizado:  "уже есть в вашем деле",
      f_tipodoc:    "Документ, удостоверяющий личность",
      f_numero:     "Номер",
      f_nacimiento: "Дата рождения",
      f_direccion:  "Налоговый адрес в Венесуэле",
      f_telefono:   "Телефон",
      f_profesion:  "Профессия",
      d_identidad:  "Удостоверение личности или паспорт",
      d_domicilio:  "Подтверждение адреса",
      /* --- RIF de la empresa --- */
      f_razon:       "Наименование компании",
      f_registro:    "Номер в торговом реестре",
      f_constitucion:"Дата учреждения",
      f_actividad:   "Вид деятельности",
      f_capital:     "Уставный капитал",
      d_acta:        "Учредительные документы",
      d_rifpersonal: "Ваш личный RIF",
      d_domemp:      "Подтверждение налогового адреса компании",
      /* --- Инвесторская виза (SAIME) --- */
      f_pasaporte:   "Номер паспорта",
      f_paisemisor:  "Страна выдачи паспорта",
      f_vencepas:    "Срок действия паспорта",
      f_consulado:   "Консульство, где оформляете",
      f_montoinv:    "Предполагаемая сумма инвестиций",
      f_motivo:      "Во что будете инвестировать",
      d_pasaporte:   "Действующий паспорт",
      d_foto:        "Фото на документы",
      d_antecedentes:"Справка о несудимости с апостилем",
      d_inversion:   "Подтверждение инвестиции",
      /* --- Вид на жительство (SAIME) --- */
      f_numvisa:     "Номер визы",
      f_ingreso:     "Дата въезда в страну",
      f_dirvzla:     "Адрес в Венесуэле",
      f_telvzla:     "Телефон в Венесуэле",
      f_civil:       "Семейное положение",
      f_ocupacion:   "Род занятий",
      o_civil:       ["Холост/не замужем", "В браке", "В разводе", "Вдовец/вдова"],
      d_visa:        "Действующая виза",
      /* --- Обмен водительских прав (INTT) --- */
      f_numlic:      "Номер прав",
      f_paislic:     "Страна выдачи",
      f_catlic:      "Категория",
      f_emisionlic:  "Дата выдачи",
      f_vencelic:    "Срок действия прав",
      d_licencia:    "Иностранные водительские права",
      d_traduccion:  "Заверенный перевод прав",
      d_medico:      "Медицинская справка",
      /* --- Учреждение компании (SAREN) --- */
      f_denominacion:"Наименование компании",
      f_denomalt:    "Запасной вариант названия",
      f_tiposoc:     "Организационно-правовая форма",
      o_tiposoc:     ["Акционерная компания (C.A.)", "Акционерное общество (S.A.)", "Общество с ограниченной ответственностью (S.R.L.)", "Индивидуальный предприниматель"],
      f_objeto:      "Предмет деятельности",
      f_domsocial:   "Юридический адрес компании",
      f_socios:      "Участники и их доли",
      d_capital:     "Подтверждение капитала (взнос или опись имущества)",
      /* --- Корпоративный счёт (банки-партнёры) --- */
      f_rifempresa:  "Номер RIF компании",
      f_tipocuenta:  "Тип счёта",
      o_tipocuenta:  ["Расчётный", "Сберегательный"],
      f_moneda:      "Валюта счёта",
      o_moneda:      ["Боливары", "Иностранная валюта (USD)"],
      f_firmantes:   "Уполномоченные лица и порядок подписи",
      f_movimiento:  "Ожидаемый месячный оборот",
      f_origenfondos:"Источник средств",
      f_ciudad:      "Город, где удобно отделение",
      d_rifempresa:  "RIF компании",
      banco_asignado:"Банк-партнёр",
      banco_pendiente:"Пока не назначен — сообщим до встречи",
      /* --- Регистрация товарного знака (SAPI) --- */
      f_signo:       "Название товарного знака",
      f_tiposigno:   "Тип обозначения",
      o_tiposigno:   ["Словесный (только слово)", "Изобразительный (только рисунок)", "Комбинированный (слово и рисунок)"],
      f_titular:     "На чьё имя регистрируется",
      o_titular:     ["На компанию", "На меня как физическое лицо"],
      f_enuso:       "Знак уже используется?",
      o_enuso:       ["Пока нет", "Да, уже использую"],
      f_productos:   "Товары или услуги, которые он охватывает",
      d_logo:        "Логотип или изображение знака",
      /* --- Трудовые регистрации (IVSS · INCES · FAOV) --- */
      f_representante:"Законный представитель (работодатель)",
      f_iniciolab:   "Дата начала деятельности",
      f_numtrab:     "Число работников для регистрации",
      d_nomina:      "Список работников",
      opcional:      "(необязательно)",
      /* --- Муниципальная лицензия (мэрия) --- */
      f_municipio:   "Муниципалитет, где находится помещение",
      f_tenencia:    "Помещение",
      o_tenencia:    ["В собственности", "Арендуется"],
      f_metros:      "Площадь помещения, м²",
      f_dirlocal:    "Точный адрес помещения или производства",
      d_inmueble:    "Свидетельство о собственности или договор аренды",
      d_bomberos:    "Заключение пожарной службы",
      /* --- Fase 01: los seis trámites que faltaban --- */
      f_paisorigen:    "Страна, выдавшая справку",
      f_autoridad:     "Выдавший орган",
      f_fechacert:     "Дата справки",
      f_idioma:        "Язык документа",
      f_docapost:      "Документ для апостиля",
      o_docapost:      ["Свидетельство о рождении", "Свидетельство о браке", "Диплом", "Другое"],
      f_fechadoc:      "Дата документа",
      f_uso:           "Для чего он нужен",
      f_ciudadvzla:    "Город в Венесуэле",
      f_municipiovzla: "Муниципалитет",
      f_tipovivienda:  "Жильё",
      o_tipovivienda:  ["В собственности", "Съёмное", "Предоставлено"],
      f_tiempores:     "Сколько живёте там",
      f_correocert:    "Почта для сертификата",
      f_tipocert:      "Тип сертификата",
      o_tipocert:      ["Физическое лицо", "Представитель компании"],
      f_nomdep:        "ФИО родственника",
      f_parentesco:    "Степень родства",
      o_parentesco:    ["Супруг(а)", "Сын или дочь", "Родитель"],
      f_centro:        "Медицинский центр",
      f_tipoexamen:    "Вид осмотра",
      o_tipoexamen:    ["Общий медосмотр", "Водительский медосмотр", "Другое"],
      d_antecorigen:   "Справка о несудимости из вашей страны",
      d_original:      "Оригинал документа для апостиля",
      d_arrendamiento: "Договор аренды или справка о проживании",
      d_recibo:        "Счёт за коммунальные услуги",
      d_pasdep:        "Паспорт родственника",
      d_vinculo:       "Документ, подтверждающий родство",
      d_fotodep:       "Фото родственника на документы",
      /* --- Fase 02: protocolización, publicación y libros --- */
      f_registromerc: "Торговый реестр для регистрации",
      f_fechafirma:   "Дата подписания документа",
      f_fechaprot:    "Дата регистрации",
      f_periodico:    "Предпочтительная коммерческая газета",
      f_tipofact:     "Как будете выставлять счета",
      o_tipofact:     ["Авторизованная типография", "Фискальный аппарат", "Согласованная система"],
      d_aranceles:    "Квитанция об оплате пошлин",
      d_actaprot:     "Зарегистрированный устав"
    }
  },

  pasos: {

    es: {
      c1:  ["Solicitud en línea ante el SAIME", "Cita consular y consignación de recaudos", "Evaluación y aprobación", "Visa TR-I estampada en el pasaporte"],
      c2:  ["Registro del extranjero con la visa vigente", "Cita para captura biométrica", "Verificación de datos migratorios", "Entrega de la cédula de identidad"],
      c3:  ["Inscripción en el portal del SENIAT", "Carga de la cédula y del comprobante de domicilio", "Validación por la oficina fiscal", "Certificado de RIF disponible"],
      c4:  ["Traducción certificada de la licencia", "Solicitud de homologación ante el INTT", "Examen médico y de conocimiento", "Emisión de la licencia venezolana"],
      c5:  ["Búsqueda y reserva del nombre", "Redacción del documento por abogado colegiado", "Revisión y firma de los socios", "Documento constitutivo listo para protocolizar"],
      c6:  ["Inscripción de la compañía en el SENIAT", "Consignación del acta constitutiva", "Asignación del número de RIF", "Certificado y clave del portal fiscal"],
      c7:  ["Elección del banco aliado", "Expediente de la empresa y de sus socios", "Cita presencial y firma de tarjetas", "Cuenta activa con banca en línea"],
      c8:  ["Búsqueda de antecedentes registrales", "Solicitud de registro ante el SAPI", "Publicación y plazo de oposición", "Concesión del certificado de marca"],
      c9:  ["Inscripción de la empresa en el IVSS", "Registro ante el INCES", "Afiliación al FAOV", "Alta de los trabajadores en los tres"],
      c10: ["Conformidad de uso del inmueble", "Solicitud de patente de industria y comercio", "Inspección municipal", "Licencia de funcionamiento otorgada"],
      c11: ["Registro como operador de comercio exterior", "Clasificación arancelaria de la mercancía", "Permisos sectoriales y certificado de origen", "Autorización de despacho aduanero"],
      c12: ["Análisis de laboratorio del producto", "Expediente técnico ante el INSAI", "Evaluación sanitaria y de calidad", "Registro sanitario otorgado"],
      c13: ["Inscripción en el sistema del RNC", "Carga de los estados financieros auditados", "Evaluación de capacidad legal y financiera", "Certificado de inscripción vigente"],
      c14: ["Solvencia laboral del Ministerio del Trabajo", "Solvencias del IVSS y del INCES", "Solvencia municipal de la alcaldía", "Expediente de solvencias al día"],
      c15: ["Perfil de inversión y sectores de interés", "Selección de activos y proyectos", "Acompañamiento del CIIP en la evaluación", "Carta de intención y cierre"],
      c16: ["Solicitud del certificado en tu país de origen", "Apostilla de La Haya sobre el certificado", "Traducción por Intérprete Público", "Antecedentes listos para presentar"],
      c17: ["Reunión de los documentos originales", "Apostilla en el país que los emitió", "Traducción por Intérprete Público", "Legalización ante el MPPRE cuando aplique"],
      c18: ["Datos de tu vivienda en Venezuela", "Verificación del registro civil o consejo comunal", "Emisión de la constancia", "Constancia guardada en tu bóveda"],
      c19: ["Solicitud ante un proveedor acreditado por SUSCERTE", "Validación presencial de tu identidad", "Emisión del certificado digital", "Firma lista para los portales del Estado"],
      c20: ["Acreditación del vínculo familiar", "Solicitud consular para cada familiar", "Evaluación del SAIME", "Visa y cédula de tus familiares"],
      c21: ["Elección del centro de salud autorizado", "Cita para la evaluación médica", "Evaluación y firma del médico", "Certificado guardado en tu bóveda"],
      c22: ["Consignación del documento en el Registro Mercantil", "Pago de aranceles registrales", "Revisión del registrador", "Acta protocolizada con personalidad jurídica"],
      c23: ["Elección del periódico mercantil", "Envío del acta protocolizada", "Publicación del extracto", "Consignación de ejemplares en el Registro"],
      c24: ["Apertura de los libros obligatorios", "Sellado y foliado en el Registro Mercantil", "Elección del sistema de facturación", "Homologación del sistema ante el SENIAT"]
    },

    en: {
      c1:  ["Online application to SAIME", "Consular appointment and paperwork", "Assessment and approval", "TR-I visa stamped in your passport"],
      c2:  ["Foreign national registration with a valid visa", "Appointment for biometric capture", "Verification of migration records", "Identity card issued"],
      c3:  ["Sign-up on the SENIAT portal", "Upload of ID and proof of address", "Validation by the tax office", "RIF certificate available"],
      c4:  ["Certified translation of your licence", "Conversion request to the INTT", "Medical and knowledge tests", "Venezuelan licence issued"],
      c5:  ["Name search and reservation", "Drafting by a registered lawyer", "Review and signature by the shareholders", "Articles ready to be filed"],
      c6:  ["Company sign-up at SENIAT", "Filing of the articles of incorporation", "RIF number assigned", "Certificate and tax portal credentials"],
      c7:  ["Choice of partner bank", "File on the company and its shareholders", "In-person appointment and signatures", "Account live with online banking"],
      c8:  ["Search of prior registrations", "Registration request to SAPI", "Publication and opposition period", "Trademark certificate granted"],
      c9:  ["Company registration with the IVSS", "Registration with the INCES", "Enrolment with the FAOV", "Staff enrolled with all three"],
      c10: ["Land-use conformity for the premises", "Application for the municipal business licence", "Municipal inspection", "Operating licence granted"],
      c11: ["Registration as a foreign-trade operator", "Tariff classification of the goods", "Sector permits and certificate of origin", "Customs clearance authorised"],
      c12: ["Laboratory analysis of the product", "Technical file submitted to INSAI", "Health and quality assessment", "Health registration granted"],
      c13: ["Sign-up in the RNC system", "Upload of audited financial statements", "Review of legal and financial capacity", "Valid registration certificate"],
      c14: ["Labour clearance from the Ministry of Labour", "IVSS and INCES clearances", "Municipal clearance from the mayor’s office", "Clearance file up to date"],
      c15: ["Investment profile and sectors of interest", "Selection of assets and projects", "CIIP support during due diligence", "Letter of intent and closing"],
      c16: ["Certificate requested in your home country", "Hague apostille added to the certificate", "Translation by a sworn public translator", "Criminal record ready to file"],
      c17: ["Original documents gathered", "Apostille in the country that issued them", "Translation by a sworn public translator", "Legalisation at the MPPRE where required"],
      c18: ["Details of your home in Venezuela", "Check by the civil registry or community council", "Certificate issued", "Certificate stored in your vault"],
      c19: ["Application to a SUSCERTE-accredited provider", "In-person identity validation", "Digital certificate issued", "Signature ready for the State portals"],
      c20: ["Proof of the family relationship", "Consular application for each relative", "SAIME assessment", "Visa and ID card for your family"],
      c21: ["Choice of an authorised health centre", "Appointment for the medical assessment", "Assessment signed by the doctor", "Certificate stored in your vault"],
      c22: ["Filing of the document at the Mercantile Registry", "Payment of registry fees", "Review by the registrar", "Articles filed, legal personality granted"],
      c23: ["Choice of the mercantile newspaper", "Submission of the filed articles", "Publication of the extract", "Copies filed back at the Registry"],
      c24: ["Opening of the mandatory books", "Books stamped and paginated at the Registry", "Choice of the invoicing system", "System approved by SENIAT"]
    },

    pt: {
      c1:  ["Solicitação em linha ao SAIME", "Entrevista consular e entrega de documentos", "Avaliação e aprovação", "Visto TR-I carimbado no passaporte"],
      c2:  ["Registo de estrangeiro com visto válido", "Marcação para recolha biométrica", "Verificação dos dados migratórios", "Entrega do cartão de identidade"],
      c3:  ["Inscrição no portal do SENIAT", "Carregamento do documento e do comprovativo de morada", "Validação pela repartição fiscal", "Certificado de RIF disponível"],
      c4:  ["Tradução certificada da carta de condução", "Pedido de equivalência ao INTT", "Exame médico e de conhecimentos", "Emissão da carta venezuelana"],
      c5:  ["Busca e reserva do nome", "Redação do documento por advogado inscrito", "Revisão e assinatura dos sócios", "Documento constitutivo pronto para protocolizar"],
      c6:  ["Inscrição da empresa no SENIAT", "Entrega do pacto social", "Atribuição do número de RIF", "Certificado e credenciais do portal fiscal"],
      c7:  ["Escolha do banco parceiro", "Processo da empresa e dos sócios", "Reunião presencial e assinaturas", "Conta ativa com banca em linha"],
      c8:  ["Pesquisa de antecedentes registais", "Pedido de registo ao SAPI", "Publicação e prazo de oposição", "Concessão do certificado de marca"],
      c9:  ["Inscrição da empresa no IVSS", "Registo no INCES", "Adesão ao FAOV", "Trabalhadores inscritos nos três"],
      c10: ["Conformidade de uso do imóvel", "Pedido de alvará de indústria e comércio", "Inspeção municipal", "Alvará de funcionamento concedido"],
      c11: ["Registo como operador de comércio externo", "Classificação pautal da mercadoria", "Licenças setoriais e certificado de origem", "Autorização de desalfandegamento"],
      c12: ["Análise laboratorial do produto", "Processo técnico junto do INSAI", "Avaliação sanitária e de qualidade", "Registo sanitário concedido"],
      c13: ["Inscrição no sistema do RNC", "Carregamento das demonstrações financeiras auditadas", "Avaliação da capacidade legal e financeira", "Certificado de inscrição válido"],
      c14: ["Certidão laboral do Ministério do Trabalho", "Certidões do IVSS e do INCES", "Certidão municipal da câmara", "Processo de certidões em dia"],
      c15: ["Perfil de investimento e setores de interesse", "Seleção de ativos e projetos", "Acompanhamento do CIIP na avaliação", "Carta de intenções e fecho"],
      c16: ["Pedido do certificado no seu país de origem", "Apostila de Haia sobre o certificado", "Tradução por Intérprete Público", "Antecedentes prontos para apresentar"],
      c17: ["Reunião dos documentos originais", "Apostila no país que os emitiu", "Tradução por Intérprete Público", "Legalização no MPPRE quando aplicável"],
      c18: ["Dados da sua moradia na Venezuela", "Verificação do registro civil ou conselho comunal", "Emissão da constância", "Constância guardada no seu cofre"],
      c19: ["Pedido a um provedor credenciado pelo SUSCERTE", "Validação presencial da sua identidade", "Emissão do certificado digital", "Assinatura pronta para os portais do Estado"],
      c20: ["Comprovação do vínculo familiar", "Pedido consular para cada familiar", "Avaliação do SAIME", "Visto e cédula dos seus familiares"],
      c21: ["Escolha do centro de saúde autorizado", "Consulta para a avaliação médica", "Avaliação e assinatura do médico", "Certificado guardado no seu cofre"],
      c22: ["Consignação do documento no Registro Mercantil", "Pagamento das taxas registrais", "Análise do registrador", "Ata protocolizada com personalidade jurídica"],
      c23: ["Escolha do jornal mercantil", "Envio da ata protocolizada", "Publicação do extrato", "Consignação dos exemplares no Registro"],
      c24: ["Abertura dos livros obrigatórios", "Selagem e numeração no Registro Mercantil", "Escolha do sistema de faturação", "Homologação do sistema no SENIAT"]
    },

    it: {
      c1:  ["Domanda online al SAIME", "Appuntamento consolare e consegna dei documenti", "Valutazione e approvazione", "Visto TR-I apposto sul passaporto"],
      c2:  ["Registrazione dello straniero con visto valido", "Appuntamento per il rilievo biometrico", "Verifica dei dati migratori", "Consegna della carta d’identità"],
      c3:  ["Iscrizione al portale del SENIAT", "Caricamento del documento e della prova di residenza", "Convalida da parte dell’ufficio fiscale", "Certificato RIF disponibile"],
      c4:  ["Traduzione giurata della patente", "Richiesta di conversione all’INTT", "Visita medica e prova teorica", "Rilascio della patente venezuelana"],
      c5:  ["Ricerca e prenotazione del nome", "Redazione dell’atto da un avvocato iscritto", "Revisione e firma dei soci", "Atto costitutivo pronto per il deposito"],
      c6:  ["Iscrizione della società al SENIAT", "Deposito dell’atto costitutivo", "Assegnazione del numero RIF", "Certificato e credenziali del portale fiscale"],
      c7:  ["Scelta della banca partner", "Fascicolo della società e dei soci", "Appuntamento in filiale e firme", "Conto attivo con banca online"],
      c8:  ["Ricerca di anteriorità", "Domanda di registrazione al SAPI", "Pubblicazione e termine di opposizione", "Rilascio del certificato di marchio"],
      c9:  ["Iscrizione dell’azienda all’IVSS", "Registrazione presso l’INCES", "Adesione al FAOV", "Dipendenti iscritti a tutti e tre"],
      c10: ["Conformità d’uso dell’immobile", "Domanda di licenza comunale", "Ispezione comunale", "Licenza di esercizio rilasciata"],
      c11: ["Registrazione come operatore del commercio estero", "Classificazione doganale della merce", "Permessi settoriali e certificato d’origine", "Autorizzazione allo sdoganamento"],
      c12: ["Analisi di laboratorio del prodotto", "Fascicolo tecnico all’INSAI", "Valutazione sanitaria e di qualità", "Registrazione sanitaria rilasciata"],
      c13: ["Iscrizione al sistema RNC", "Caricamento dei bilanci certificati", "Valutazione della capacità legale e finanziaria", "Certificato d’iscrizione valido"],
      c14: ["Certificazione del Ministero del Lavoro", "Certificazioni IVSS e INCES", "Certificazione comunale", "Fascicolo delle certificazioni aggiornato"],
      c15: ["Profilo d’investimento e settori d’interesse", "Selezione di asset e progetti", "Affiancamento del CIIP nella valutazione", "Lettera d’intenti e closing"],
      c16: ["Richiesta del certificato nel tuo paese d'origine", "Apostille dell'Aia sul certificato", "Traduzione da Interprete Pubblico", "Casellario pronto da presentare"],
      c17: ["Raccolta dei documenti originali", "Apostille nel paese che li ha emessi", "Traduzione da Interprete Pubblico", "Legalizzazione presso il MPPRE se necessario"],
      c18: ["Dati della tua abitazione in Venezuela", "Verifica dell'anagrafe o del consiglio comunale", "Rilascio del certificato", "Certificato conservato nel tuo archivio"],
      c19: ["Richiesta a un fornitore accreditato da SUSCERTE", "Convalida di persona della tua identità", "Rilascio del certificato digitale", "Firma pronta per i portali dello Stato"],
      c20: ["Prova del legame familiare", "Domanda consolare per ogni familiare", "Valutazione del SAIME", "Visto e documento per i tuoi familiari"],
      c21: ["Scelta della struttura sanitaria autorizzata", "Appuntamento per la visita medica", "Visita e firma del medico", "Certificato conservato nel tuo archivio"],
      c22: ["Deposito dell’atto al Registro delle Imprese", "Pagamento dei diritti di registro", "Esame del conservatore", "Atto depositato, personalità giuridica acquisita"],
      c23: ["Scelta del giornale commerciale", "Invio dell’atto depositato", "Pubblicazione dell’estratto", "Consegna delle copie al Registro"],
      c24: ["Apertura dei libri obbligatori", "Vidimazione e numerazione al Registro", "Scelta del sistema di fatturazione", "Omologazione del sistema presso il SENIAT"]
    },

    zh: {
      c1:  ["向 SAIME 在线提交申请", "领事预约并递交材料", "审核与批准", "TR-I 签证已贴入护照"],
      c2:  ["持有效签证办理外国人登记", "预约采集生物特征", "核验出入境记录", "发放身份证"],
      c3:  ["在 SENIAT 门户注册", "上传身份证件与住址证明", "税务局审核", "RIF 证明可下载"],
      c4:  ["驾照的认证翻译", "向 INTT 提交换发申请", "体检与知识考试", "签发委内瑞拉驾照"],
      c5:  ["名称查询与预留", "由注册律师起草文件", "股东审阅并签署", "章程可提交登记"],
      c6:  ["公司在 SENIAT 注册", "提交公司章程", "分配 RIF 号码", "证明与税务门户账号"],
      c7:  ["选择合作银行", "公司及股东资料", "到场预约与签字", "账户启用并开通网银"],
      c8:  ["在先商标检索", "向 SAPI 提交注册申请", "公告与异议期", "核发商标证书"],
      c9:  ["公司在 IVSS 登记", "在 INCES 登记", "加入 FAOV", "员工在三处完成登记"],
      c10: ["场所用途合规证明", "申请市政营业执照", "市政检查", "核发营业执照"],
      c11: ["注册为对外贸易经营者", "货物的税则归类", "行业许可与原产地证", "准予海关放行"],
      c12: ["产品实验室检测", "向 INSAI 提交技术档案", "卫生与质量评估", "核发卫生注册"],
      c13: ["在 RNC 系统登记", "上传经审计的财务报表", "法律与财务能力评估", "有效的登记证书"],
      c14: ["劳动部劳动清税证明", "IVSS 与 INCES 清税证明", "市政清税证明", "清税档案齐备"],
      c15: ["投资意向与关注行业", "筛选资产与项目", "CIIP 协助尽职调查", "意向书与交割"],
      c16: ["在原籍国申请无犯罪记录证明", "为证明办理海牙认证", "由公共翻译员翻译", "无犯罪记录可提交"],
      c17: ["收齐原件材料", "在签发国办理海牙认证", "由公共翻译员翻译", "必要时在外交部完成合法化"],
      c18: ["填写你在委内瑞拉的住所信息", "由民事登记处或社区委员会核实", "出具住所证明", "证明存入你的档案库"],
      c19: ["向 SUSCERTE 认证的服务商提出申请", "现场核验你的身份", "签发数字证书", "可用于政府各门户网站"],
      c20: ["证明家庭关系", "为每位家属提出领事申请", "SAIME 审核", "家属取得签证与身份证"],
      c21: ["选择获授权的医疗机构", "预约体检", "医生检查并签字", "证明存入你的档案库"],
      c22: ["向商事登记处提交文件", "缴纳登记规费", "登记官审查", "章程登记完成，取得法人资格"],
      c23: ["选择商事报纸", "提交已登记的章程", "刊登摘要", "将样报交回登记处"],
      c24: ["开立法定账簿", "在商事登记处盖章编号", "选择开票系统", "系统通过 SENIAT 认证"]
    },

    ru: {
      c1:  ["Онлайн-заявление в SAIME", "Запись в консульство и подача документов", "Рассмотрение и одобрение", "Виза TR-I вклеена в паспорт"],
      c2:  ["Регистрация иностранца с действующей визой", "Запись на снятие биометрии", "Проверка миграционных данных", "Выдача удостоверения личности"],
      c3:  ["Регистрация на портале SENIAT", "Загрузка удостоверения и подтверждения адреса", "Проверка налоговой инспекцией", "Свидетельство RIF доступно"],
      c4:  ["Заверенный перевод водительских прав", "Заявление на обмен в INTT", "Медосмотр и теоретический экзамен", "Выдача венесуэльских прав"],
      c5:  ["Поиск и резервирование названия", "Подготовка документа адвокатом", "Проверка и подпись учредителей", "Устав готов к регистрации"],
      c6:  ["Регистрация компании в SENIAT", "Подача учредительных документов", "Присвоение номера RIF", "Свидетельство и доступ к налоговому порталу"],
      c7:  ["Выбор банка-партнёра", "Досье компании и её участников", "Личная встреча и подписи", "Счёт открыт, подключён интернет-банк"],
      c8:  ["Проверка ранее зарегистрированных знаков", "Заявка на регистрацию в SAPI", "Публикация и срок для возражений", "Выдача свидетельства на знак"],
      c9:  ["Регистрация компании в IVSS", "Регистрация в INCES", "Присоединение к FAOV", "Работники зарегистрированы во всех трёх"],
      c10: ["Подтверждение назначения помещения", "Заявление на муниципальную лицензию", "Муниципальная проверка", "Лицензия на деятельность выдана"],
      c11: ["Регистрация как участника ВЭД", "Тарифная классификация товара", "Отраслевые разрешения и сертификат происхождения", "Разрешение на таможенное оформление"],
      c12: ["Лабораторный анализ продукции", "Технический пакет в INSAI", "Санитарная оценка и оценка качества", "Санитарная регистрация выдана"],
      c13: ["Регистрация в системе RNC", "Загрузка аудированной отчётности", "Оценка правоспособности и финансов", "Действующее свидетельство о регистрации"],
      c14: ["Справка Министерства труда", "Справки IVSS и INCES", "Муниципальная справка", "Пакет справок в порядке"],
      c15: ["Инвестиционный профиль и интересующие отрасли", "Отбор активов и проектов", "Сопровождение CIIP при оценке", "Письмо о намерениях и закрытие"],
      c16: ["Запрос справки в стране происхождения", "Гаагский апостиль на справке", "Перевод присяжным переводчиком", "Справка готова к подаче"],
      c17: ["Сбор оригиналов документов", "Апостиль в стране выдачи", "Перевод присяжным переводчиком", "Легализация в MPPRE при необходимости"],
      c18: ["Данные о вашем жилье в Венесуэле", "Проверка ЗАГСа или общинного совета", "Выдача справки", "Справка в вашем хранилище"],
      c19: ["Заявка аккредитованному SUSCERTE провайдеру", "Личная проверка вашей личности", "Выпуск цифрового сертификата", "Подпись готова для госпорталов"],
      c20: ["Подтверждение родственной связи", "Консульская заявка на каждого родственника", "Рассмотрение в SAIME", "Виза и удостоверение для близких"],
      c21: ["Выбор аккредитованного медцентра", "Запись на медосмотр", "Осмотр и подпись врача", "Справка в вашем хранилище"],
      c22: ["Подача документа в Торговый реестр", "Оплата регистрационных пошлин", "Проверка регистратором", "Устав зарегистрирован, получена правосубъектность"],
      c23: ["Выбор коммерческой газеты", "Направление зарегистрированного устава", "Публикация выписки", "Сдача экземпляров в реестр"],
      c24: ["Заведение обязательных книг", "Прошивка и нумерация в реестре", "Выбор системы выставления счетов", "Согласование системы с SENIAT"]
    }

  }
};
